name: Create Image

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pushCertsContainer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Up Docker Build
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.streem.tech
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: harbor.streem.tech/streemtech/certs-image:latest
          context: .
          file: dockerfile
